Repository mohamed-taman/Springy-Store-Microservices, pull requests merged in 2020-04, with the labels that each got.

#4 Feature/adding apis manual testing script
  .gitignore
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  README.md
  docs/stage1/Springy Store Application MS Landscape.png
  docs/stage1/source/Springy Store Application MS Landscape.drawio
  mvnw
  mvnw.cmd
  product-composite-service/.gitignore
  product-composite-service/pom.xml
  product-composite-service/src/main/resources/application.yaml
  product-service/.gitignore
  product-service/.mvn/wrapper/MavenWrapperDownloader.java
  product-service/.mvn/wrapper/maven-wrapper.jar
  product-service/.mvn/wrapper/maven-wrapper.properties
  product-service/mvnw
  product-service/mvnw.cmd
  product-service/pom.xml
  product-service/src/main/resources/application.yaml
  recommendation-service/.gitignore
  recommendation-service/.mvn/wrapper/MavenWrapperDownloader.java
  recommendation-service/.mvn/wrapper/maven-wrapper.jar
  recommendation-service/.mvn/wrapper/maven-wrapper.properties
  recommendation-service/mvnw
  recommendation-service/mvnw.cmd
  recommendation-service/pom.xml
  recommendation-service/src/main/resources/application.yaml
  review-service/.gitignore
  review-service/.mvn/wrapper/MavenWrapperDownloader.java
  review-service/.mvn/wrapper/maven-wrapper.jar
  review-service/.mvn/wrapper/maven-wrapper.properties
  review-service/mvnw
  review-service/mvnw.cmd
  review-service/pom.xml
  review-service/src/main/resources/application.yaml
  run-em-all.sh
  setup.sh
  stop-em-all.sh
  store-utils/pom.xml
  test-em-all.sh
Labels: documentation, enhancement

#6 Dockerize product microservice
  product-service/Dockerfile
  product-service/src/main/resources/application.yaml
  store-chassis/pom.xml
Labels: enhancement

#11 Review service dockerization
  product-service/src/main/resources/application.yaml
  review-service/Dockerfile
  review-service/src/main/resources/application.yaml
Labels: enhancement

#12 Recommendation service dockerization closes #9
  recommendation-service/Dockerfile
  recommendation-service/src/main/resources/application.yaml
Labels: enhancement

#14 Product composite service containerization closes #10
  docker-compose.yml
  product-composite-service/Dockerfile
  product-composite-service/src/main/resources/META-INF/additional-spring-configuration-metadata.json
  product-composite-service/src/main/resources/application.yaml
  test-em-all.sh
Labels: enhancement

#17 Adding maven docker plugin closes #16
  product-composite-service/Dockerfile
  product-composite-service/pom.xml
  product-service/Dockerfile
  product-service/pom.xml
  recommendation-service/Dockerfile
  recommendation-service/pom.xml
  review-service/Dockerfile
  review-service/pom.xml
  store-api/pom.xml
  store-chassis/pom.xml
  store-utils/pom.xml
Labels: enhancement

#20 Use mvnw instead of mvn
  run-em-all.sh
  setup.sh
Labels: good first issue

#19 Use profile to activate dockerfile-maven-plugin based on the presence of a Dockerfile.
  product-composite-service/pom.xml
  product-service/pom.xml
  recommendation-service/pom.xml
  review-service/pom.xml
  store-chassis/pom.xml
Labels: enhancement, good first issue

#25 Simplify maven build.
  README.md
  pom.xml
  product-composite-service/pom.xml
  product-service/pom.xml
  recommendation-service/pom.xml
  review-service/pom.xml
  run-em-all.sh
  setup.sh
  store-api/pom.xml
  store-build-chassis/pom.xml
  store-service-chassis/pom.xml
  store-utils/pom.xml
Labels: enhancement, good first issue

#27 Swaggerized the product composite
  README.md
  product-composite-service/pom.xml
  product-composite-service/src/main/java/com/siriusxi/ms/store/pcs/ProductCompositeServiceApplication.java
  product-composite-service/src/main/java/com/siriusxi/ms/store/pcs/config/ProductCompositeConfiguration.java
  product-composite-service/src/main/resources/META-INF/additional-spring-configuration-metadata.json
  product-composite-service/src/main/resources/application.yaml
  product-composite-service/src/test/java/com/siriusxi/ms/store/pcs/ProductCompositeServiceApplicationTests.java
  product-service/pom.xml
  recommendation-service/pom.xml
  review-service/pom.xml
  store-api/pom.xml
  store-api/src/main/java/com/siriusxi/ms/store/api/composite/product/ProductCompositeService.java
  store-api/src/main/java/com/siriusxi/ms/store/api/core/product/ProductService.java
  store-api/src/main/java/com/siriusxi/ms/store/api/core/recommendation/RecommendationService.java
  store-api/src/main/java/com/siriusxi/ms/store/api/core/review/ReviewService.java
  store-build-chassis/pom.xml
  store-utils/pom.xml
  test-em-all.sh
Labels: documentation, enhancement

#30 Add custom banners to microservices
  product-composite-service/src/main/resources/banner.txt
  product-service/src/main/resources/banner.txt
  recommendation-service/src/main/resources/banner.txt
  review-service/src/main/resources/banner.txt
Labels: enhancement

#47 Set mongodb auto-index-creation true
  product-service/src/main/resources/application.yaml
  product-service/src/test/java/com/siriusxi/ms/store/ps/PersistenceTests.java
  recommendation-service/src/main/resources/application.yaml
  recommendation-service/src/test/java/com/siriusxi/ms/store/rs/PersistenceTests.java
Labels: bug, good first issue

#49 Feature/decompose service layer resolves #46
  product-service/src/main/java/com/siriusxi/ms/store/ps/api/ProductController.java
  product-service/src/main/java/com/siriusxi/ms/store/ps/service/ProductMapper.java
  product-service/src/main/java/com/siriusxi/ms/store/ps/service/ProductServiceImpl.java
  product-service/src/test/java/com/siriusxi/ms/store/ps/MapperTests.java
  product-service/src/test/java/com/siriusxi/ms/store/ps/ProductServiceApplicationTests.java
  recommendation-service/src/main/java/com/siriusxi/ms/store/rs/api/RecommendationController.java
  recommendation-service/src/main/java/com/siriusxi/ms/store/rs/controller/RecommendationServiceImpl.java
  recommendation-service/src/main/java/com/siriusxi/ms/store/rs/service/RecommendationMapper.java
  recommendation-service/src/main/java/com/siriusxi/ms/store/rs/service/RecommendationServiceImpl.java
  recommendation-service/src/test/java/com/siriusxi/ms/store/rs/MapperTests.java
  recommendation-service/src/test/java/com/siriusxi/ms/store/rs/RecommendationServiceApplicationTests.java
  review-service/src/main/java/com/siriusxi/ms/store/revs/api/ReviewController.java
  review-service/src/main/java/com/siriusxi/ms/store/revs/service/ReviewMapper.java
  review-service/src/main/java/com/siriusxi/ms/store/revs/service/ReviewServiceImpl.java
  review-service/src/test/java/com/siriusxi/ms/store/revs/MapperTests.java
  review-service/src/test/java/com/siriusxi/ms/store/revs/ReviewServiceApplicationTests.java
  store-api/src/main/java/com/siriusxi/ms/store/api/composite/StoreEndpoint.java
  store-api/src/main/java/com/siriusxi/ms/store/api/composite/StoreService.java
  store-api/src/main/java/com/siriusxi/ms/store/api/core/product/ProductEndpoint.java
  store-api/src/main/java/com/siriusxi/ms/store/api/core/product/ProductService.java
  store-api/src/main/java/com/siriusxi/ms/store/api/core/product/dto/Product.java
  store-api/src/main/java/com/siriusxi/ms/store/api/core/recommendation/RecommendationEndpoint.java
  store-api/src/main/java/com/siriusxi/ms/store/api/core/recommendation/RecommendationService.java
  store-api/src/main/java/com/siriusxi/ms/store/api/core/recommendation/dto/Recommendation.java
  store-api/src/main/java/com/siriusxi/ms/store/api/core/review/ReviewEndpoint.java
  store-api/src/main/java/com/siriusxi/ms/store/api/core/review/ReviewService.java
  store-api/src/main/java/com/siriusxi/ms/store/api/core/review/dto/Review.java
  store-service/src/main/java/com/siriusxi/ms/store/pcs/api/StoreController.java
  store-service/src/main/java/com/siriusxi/ms/store/pcs/controller/StoreServiceImpl.java
  store-service/src/main/java/com/siriusxi/ms/store/pcs/integration/StoreIntegration.java
  store-service/src/main/java/com/siriusxi/ms/store/pcs/service/StoreServiceImpl.java
  store-service/src/test/java/com/siriusxi/ms/store/pcs/StoreServiceApplicationTests.java
Labels: enhancement

#51 Review service is database version controlled. resolves #40
  review-service/pom.xml
  review-service/src/main/java/com/siriusxi/ms/store/revs/ReviewServiceApplication.java
  review-service/src/main/java/com/siriusxi/ms/store/revs/persistence/ReviewEntity.java
  review-service/src/main/resources/application.yaml
  review-service/src/main/resources/db/migration/V0__Create_Intial_Schema.sql
  review-service/src/test/java/com/siriusxi/ms/store/revs/PersistenceTests.java
  review-service/src/test/java/com/siriusxi/ms/store/revs/ReviewServiceApplicationTests.java
  review-service/src/test/resources/application-test.yaml
  store-build-chassis/pom.xml
  store-service-chassis/pom.xml
Labels: enhancement

#54 Add new reactive Diagram.
  docs/stage1/app_ms_landscape.png
Labels: enhancement

#55 Convert System operations to be read operation Reactive and create and delete to be message-driven based operations.
  README.md
  docker-compose-kafka.yml
  docker-compose-partitions.yml
  docker-compose.yml
  product-service/pom.xml
  product-service/src/main/java/com/siriusxi/ms/store/ps/api/ProductController.java
  product-service/src/main/java/com/siriusxi/ms/store/ps/infra/MessageProcessor.java
  product-service/src/main/java/com/siriusxi/ms/store/ps/persistence/ProductRepository.java
  product-service/src/main/java/com/siriusxi/ms/store/ps/service/ProductServiceImpl.java
  product-service/src/main/resources/application.yaml
  product-service/src/test/java/com/siriusxi/ms/store/ps/MapperTests.java
  product-service/src/test/java/com/siriusxi/ms/store/ps/PersistenceTests.java
  product-service/src/test/java/com/siriusxi/ms/store/ps/ProductServiceApplicationTests.java
  recommendation-service/pom.xml
  recommendation-service/src/main/java/com/siriusxi/ms/store/rs/api/RecommendationController.java
  recommendation-service/src/main/java/com/siriusxi/ms/store/rs/infra/MessageProcessor.java
  recommendation-service/src/main/java/com/siriusxi/ms/store/rs/persistence/RecommendationEntity.java
  recommendation-service/src/main/java/com/siriusxi/ms/store/rs/persistence/RecommendationRepository.java
  recommendation-service/src/main/java/com/siriusxi/ms/store/rs/service/RecommendationServiceImpl.java
  recommendation-service/src/main/resources/application.yaml
  recommendation-service/src/test/java/com/siriusxi/ms/store/rs/MapperTests.java
  recommendation-service/src/test/java/com/siriusxi/ms/store/rs/PersistenceTests.java
  recommendation-service/src/test/java/com/siriusxi/ms/store/rs/RecommendationServiceApplicationTests.java
  review-service/src/main/java/com/siriusxi/ms/store/revs/api/ReviewController.java
  review-service/src/main/java/com/siriusxi/ms/store/revs/config/ReviewServiceConfiguration.java
  review-service/src/main/java/com/siriusxi/ms/store/revs/infra/MessageProcessor.java
  review-service/src/main/java/com/siriusxi/ms/store/revs/service/ReviewServiceImpl.java
  review-service/src/main/resources/application.yaml
  review-service/src/test/java/com/siriusxi/ms/store/revs/MapperTests.java
  review-service/src/test/java/com/siriusxi/ms/store/revs/PersistenceTests.java
  review-service/src/test/java/com/siriusxi/ms/store/revs/ReviewServiceApplicationTests.java
  store-api/src/main/java/com/siriusxi/ms/store/api/composite/StoreEndpoint.java
  store-api/src/main/java/com/siriusxi/ms/store/api/composite/StoreService.java
  store-api/src/main/java/com/siriusxi/ms/store/api/core/product/ProductEndpoint.java
  store-api/src/main/java/com/siriusxi/ms/store/api/core/product/ProductService.java
  store-api/src/main/java/com/siriusxi/ms/store/api/core/recommendation/RecommendationEndpoint.java
  store-api/src/main/java/com/siriusxi/ms/store/api/core/recommendation/RecommendationService.java
  store-api/src/main/java/com/siriusxi/ms/store/api/core/review/ReviewEndpoint.java
  store-api/src/main/java/com/siriusxi/ms/store/api/core/review/ReviewService.java
  store-api/src/main/java/com/siriusxi/ms/store/api/event/Event.java
  store-build-chassis/pom.xml
  store-service-chassis/pom.xml
  store-service/src/main/java/com/siriusxi/ms/store/pcs/api/StoreController.java
  store-service/src/main/java/com/siriusxi/ms/store/pcs/config/StoreServiceConfiguration.java
  store-service/src/main/java/com/siriusxi/ms/store/pcs/integration/StoreIntegration.java
  store-service/src/main/java/com/siriusxi/ms/store/pcs/service/StoreServiceImpl.java
  store-service/src/main/resources/application.yaml
  store-service/src/test/java/com/siriusxi/ms/store/pcs/IsSameEvent.java
  store-service/src/test/java/com/siriusxi/ms/store/pcs/IsSameEventTests.java
  store-service/src/test/java/com/siriusxi/ms/store/pcs/MessagingTests.java
  store-service/src/test/java/com/siriusxi/ms/store/pcs/ReactorTests.java
  store-service/src/test/java/com/siriusxi/ms/store/pcs/StoreServiceApplicationTests.java
  store-utils/src/main/java/com/siriusxi/ms/store/util/exceptions/EventProcessingException.java
  test-em-all.sh
Labels: bug, documentation, enhancement

#58 implementing 'convert to record TODOs'
  store-common/store-api/src/main/java/com/siriusxi/ms/store/api/composite/dto/ProductAggregate.java
  store-common/store-api/src/main/java/com/siriusxi/ms/store/api/composite/dto/RecommendationSummary.java
  store-common/store-api/src/main/java/com/siriusxi/ms/store/api/composite/dto/ReviewSummary.java
  store-common/store-api/src/main/java/com/siriusxi/ms/store/api/composite/dto/ServiceAddresses.java
  store-services/store-service/src/main/java/com/siriusxi/ms/store/pcs/StoreServiceApplication.java
  store-services/store-service/src/main/java/com/siriusxi/ms/store/pcs/service/StoreServiceImpl.java
  store-services/store-service/src/test/java/com/siriusxi/ms/store/pcs/MessagingTests.java
Labels: enhancement

#59 adding code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation
